WebApplication1/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication1/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AuthorizationController : Controller
    {
        //
        // GET: /Authorization/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication1/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ContactsController : Controller
    {
        //
        // GET: /Contacts/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication1/Views/Authorization/Index.cshtml
<script data-main="/Scripts/auth" src="/Scripts/require.js"></script>
<div class="container">
    <!--NAVIGATION PANEL-->
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            @Html.ActionLink("Универсальный решатель системных задач", "", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink("О проекте", "", "About")
                </li>
                <li>
                    @Html.ActionLink("Контакты", "", "Contacts")
                </li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <li>
                    @Html.ActionLink("Войти", "", "Authorization")
                </li>
                <li>
                    @Html.ActionLink("Зарегистрироваться", "", "Registration")
                </li>
            </ul>
        </div>
    </nav>
    <!--BODY CONTENT-->
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="form-signin" role="form">
                <h2 class="form-signin-heading">Введите ваш логин и пароль</h2>
                <input id="login" type="text" class="form-control" placeholder="Ваш логин" required autofocus>
                <input id="pass" type="password" class="form-control" placeholder="Пароль" required>
                <button id="signin" data-loading-text="Идет авторизация..." class="btn btn-lg btn-primary btn-block" type="button"> Войти </button>
            </form>
            <div id="resultAuth"></div>
        </div>
    </div>
    <!--FOOTER-->
    <div class="navbar-fixed-bottom row-fluid">
        <div class="container">
            <p class="text-muted">Универсальный решатель системных задач. Авторы Колесников Антон, Кузнецов Евгений. @DateTime.Now.Year</p>
        </div>
    </div>
</div>    
<script id="resultAuthTmpl" type="text/template">
    {{#errors}}
    <div class="alert alert-danger">
        <p>  Ошибка! </p>
        <p>{{ErrorDescription}}</p>        
    </div>
    {{/errors}}
</script>