WebApplication1/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication1/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ContactsController : Controller
    {
        //
        // GET: /Contacts/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication1/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class RegistrationController : Controller
    {
        //
        // GET: /Registration/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication1/Views/About/Index.cshtml
<div class="container">
    <!--NAVIGATION PANEL-->
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            @Html.ActionLink("Универсальный решатель системных задач", "", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink("О проекте", "", "About")
                </li>
                <li>
                    @Html.ActionLink("Контакты", "", "Contacts")
                </li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <li>
                    @Html.ActionLink("Войти", "", "Authorization")
                </li>
                <li>
                    @Html.ActionLink("Зарегистрироваться", "", "Registration")
                </li>
            </ul>
        </div>
    </nav>
    <!--BODY CONTENT-->
    <!--FOOTER-->
    <div class="navbar-fixed-bottom row-fluid">
        <div class="container">
            <p class="text-muted">Универсальный решатель системных задач. Авторы Колесников Антон, Кузнецов Евгений. @DateTime.Now.Year</p>
        </div>
    </div>
</div>    